model:
  base_learning_rate: 4.5e-06
  target: taming.models.refinement_ae.RefinementAE
  params:
    ckpt_path: logs/2023-04-03T01-46-12_places256_refinement_tamencoder/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 8192
    image_key: "image"
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/places256_vqgan_BASE/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 8192
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.PIPSWithDiscriminator
      params:
        pixelloss_weight: 1.0
        perceptual_weight: 1.0
        r1_weight: 0.0
        disc_conditional: False
        disc_in_channels: 4 # 3 + 256
        disc_start: 1
        disc_weight: 0.8
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    train:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/data_large
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'train'
