model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan.VQModel
  params:
    # ckpt_path: logs/ckpt/coco.ckpt
    embed_dim: 256
    n_embed: 8192
    image_key: "image"
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    train:
      target: taming.data.owt.AnyImageFolder
      params:
        size: 256
        dataroot: "/data/Haiwei/clevr/clevr/256"
        crop_size: 256
        extension: 'png'
