model:
  base_learning_rate: 4.5e-06
  target: taming.models.decoder.unet.RefinementUNet
  params:
    ckpt_path: logs/2023-10-30T14-29-47_celeba_decoder_unet/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 1024
    image_key: image
    freeze_firststage: false
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    first_stage_model_type: 'decoder'
    first_stage_config:
      target: taming.models.decoder.refinementAE.RefinementAE
      params:
        ckpt_path: logs/2023-10-26T08-39-37_celeba_decoder/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        image_key: image
        restriction: false
        first_stage_model_type: 'vae'
        first_stage_config:
          target: taming.models.vqgan.VQModel
          params:
            ckpt_path: logs/2023-10-16T05-50-29_celebA_vqgan/checkpoints/last.ckpt
            embed_dim: 256
            n_embed: 1024
            ddconfig:
              padding_free: false
              double_z: false
              z_channels: 256
              resolution: 256
              in_channels: 3
              out_ch: 3
              ch: 128
              ch_mult:
              - 1
              - 1
              - 2
              - 2
              - 4
              num_res_blocks: 2
              attn_resolutions:
              - 16
              dropout: 0.0
            lossconfig:
              target: taming.modules.losses.DummyLoss
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.PIPSWithDiscriminator
          params:
            pixelloss_weight: 0.0
            perceptual_weight: 0.1
            r1_weight: 1.0
            disc_conditional: false
            disc_in_channels: 4
            disc_start: 0
            disc_weight: 1.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.PIPSWithDiscriminator
      params:
        pixelloss_weight: 0.1
        perceptual_weight: 0.1
        r1_weight: 1.0
        disc_conditional: false
        disc_in_channels: 4
        disc_start: 0
        disc_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    train:
      target: taming.data.places365.Places
      params:
        dataroot: /home/chenh/data/celeba_hq/train
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'train'
    test:
      target: taming.data.places365.Places
      params:
        dataroot: /home/chenh/data/celeba_hq/val
        maskroot: /home/chenh/data/celeba_hq/masks_val_256_small_eval
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'test'
