model:
  base_learning_rate: 4.5e-06
  target: taming.models.attgan.ATTVQModel
  params:
    embed_dim: 512
    n_embed: 1024
    image_key: "image"
    bertconfig:
      dim: 512
      pos_dim: 2
      from_len: 256 # 16x16
      to_len: 1024 # should be the same as n_embed
      from_dim: 512 
      to_dim: 512 # should be the same as embed_dim
      num_heads: 1
      attention_dropout: 0.12
      integration: 'none'
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.ATTPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    train:
      target: taming.data.owt.OWTBase
      params:
        size: 272
        dataroot: "/home/ICT2000/chenh/Datasets/USC_Galen_Center"
        crop_size: 256
# data:
#   target: main.DataModuleFromConfig
#   params:
#     batch_size: 8
#     train:
#       target: taming.data.owt.OWTMulti
#       params:
#         size: 272
#         dataroot: "/home/ICT2000/chenh/Datasets/owt.txt"
#         multiplier: 1
#         crop_size: 256