model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan.VQModel
  params:
    ckpt_path: logs/ckpt/coco.ckpt
    embed_dim: 256
    n_embed: 8192
    image_key: "image"
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    train:
      target: taming.data.owt.OWTBase
      params:
        size: 544
        # dataroot: "/home/ICT2000/chenh/Datasets/Catalina"
        # dataroot: "/vgldb1/OWT/07-10-2020/RealData/ZhengHouse/OutputImageSegmentation/images/"
        dataroot: "/home/ICT2000/chenh/Datasets/USC_Galen_Center"
        crop_size: 256
# data:
#   target: main.DataModuleFromConfig
#   params:
#     batch_size: 8
#     train:
#       target: taming.data.owt.OWTMulti
#       params:
#         size: 272
#         dataroot: "/home/ICT2000/chenh/Datasets/owt_debug.txt"
#         crop_size: 256