model:
  base_learning_rate: 4.5e-05
  target: taming.models.impgan.ImplicitDecoder
  # ckpt_path: logs/2022-09-30T22-05-35_debug_mlp_noshift/checkpoints/last.ckpt
  params:
    ddconfig:
      padding_free: true
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    mlp_config:
      nf_in: 276  #276 # 532 # 2x5x2 + 256
      nf_out: 3
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/2022-08-12T07-21-07_usc_512_pfvqgan/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 8192
        ddconfig:
          padding_free: true
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 0.0
    crop_res: 256
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    train:
      target: taming.data.owt.OWTBase
      params:
        size: 512
        dataroot: "/home/ICT2000/chenh/Datasets/USC_Galen_Center"
        crop_size: 512
        onehot_segmentation: true

