model:
  disable_zero_padding: false
  base_learning_rate: 4.5e-06
  target: taming.models.att_transformer.AttTransformer
  params:
    cond_stage_key: "image"
    transformer_config:
      target: taming.modules.transformer.mingpt.ATTGPT
      params:
        vocab_size: 128
        block_size: 256
        n_layer: 24
        n_head: 16
        n_embd: 512
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
    first_stage_config:
      target: taming.models.attgan.ATTVQModel
      params:
        ckpt_path: logs/2022-11-06T10-57-36_owt_attvqgan_cl128/checkpoints/last.ckpt
        embed_dim: 512
        n_embed: 128
        image_key: "image"
        bertconfig:
          dim: 512
          pos_dim: 2
          from_len: 256 
          to_len: 128 
          from_dim: 512 
          to_dim: 512
          num_heads: 1
          attention_dropout: 0.0
          integration: 'none'
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    train:
      target: taming.data.owt.OWTBase
      params:
        size: 272
        dataroot: "/home/ICT2000/chenh/Datasets/USC_Galen_Center"
        crop_size: 256
        onehot_segmentation: true
