model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan.VQSegmentationModel
  params:
    embed_dim: 128
    n_embed: 1024
    image_key: "segmentation"
    n_labels: 3
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.segmentation.BCELossWithQuant
      params:
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    train:
      target: taming.data.owt.OWTBase
      params:
        size: 272
        # dataroot: "/home/ICT2000/chenh/Datasets/Catalina"
        dataroot: "/home/ICT2000/chenh/Datasets/USC_Galen_Center"
        crop_size: 256
        onehot_segmentation: true
