model:
  base_learning_rate: 4.5e-06
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    # ckpt_path: /home/ICT2000/chenh/taming-transformers/logs/2022-08-06T05-29-58_usc_512_transformer_nc/checkpoints/last.ckpt
    first_stage_key: "segmentation"
    # cond_stage_key: "segmentation"
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 512  # = 256 + 256 = dim(vqgan_latent_space,16x16) 
        n_layer: 24
        n_head: 16
        n_embd: 1408
        embd_pdrop: 0.1
        resid_pdrop: 0.1
        attn_pdrop: 0.1
    first_stage_config:
      target: taming.models.vqgan.VQSegmentationModel
      params:
        ckpt_path: /home/ICT2000/chenh/taming-transformers/logs/2022-08-10T02-20-22_usc_512_pfvqgan_cond/checkpoints/last.ckpt
        embed_dim: 128
        n_embed: 1024
        image_key: "segmentation"
        n_labels: 3
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config: "__is_unconditional__"
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    train:
      target: taming.data.owt.OWTBase
      params:
        size: 512
        # dataroot: "/home/ICT2000/chenh/Datasets/Catalina"
        dataroot: "/home/ICT2000/chenh/Datasets/USC_Galen_Center"
        # dataroot: "/vgldb1/OWT/07-10-2020/RealData/Catalina/OutputImageSegmentation_Catalina/Images/"
        crop_size: 256
        multiscale_factor: 0.5

