model:
  base_learning_rate: 4.5e-06
  target: taming.models.refinement_ae.RefinementAE
  params:
    ckpt_path: logs/2023-06-04T12-39-32_decoder_perceptual_gitfinetune_safe/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 1024
    image_key: image
    restriction: false
    first_stage_model_type: 'transformer'
    first_stage_config:
      target: taming.models.maskgit.MaskGIT
      params:
        ckpt_path: /data/Haiwei/taming_ckpts/2023-05-18T07-39-35_places256_maskgit_1024_cont/checkpoints/last.ckpt
        cond_stage_key: segmentation
        sampling_ratio: 0.4
        attention_extent: mask
        mask_on_latent: true
        transformer_config:
          target: taming.modules.transformer.mingpt.GPT
          params:
            vocab_size: 1025
            block_size: 257  # 257
            n_layer: 24 # 24,40
            n_head: 16
            n_embd: 1408
            embd_pdrop: 0.0
            resid_pdrop: 0.0
            attn_pdrop: 0.0
        first_stage_config:
          target: taming.models.vqgan.VQModel
          params:
            ckpt_path: logs/places256_vqgan1024_BASE/checkpoints/last.ckpt
            embed_dim: 256
            n_embed: 1024
            ddconfig:
              padding_free: false
              double_z: false
              z_channels: 256
              resolution: 256
              in_channels: 3
              out_ch: 3
              ch: 128
              ch_mult:
              - 1
              - 1
              - 2
              - 2
              - 4
              num_res_blocks: 2
              attn_resolutions:
              - 16
              dropout: 0.0
            lossconfig:
              target: taming.modules.losses.DummyLoss
        cond_stage_config: "__is_unconditional__"          
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.PIPSWithDiscriminator
      params:
        pixelloss_weight: 0.0
        perceptual_weight: 0.1
        r1_weight: 1.0
        disc_conditional: false
        disc_in_channels: 4
        disc_start: 1
        disc_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    train:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/data_large
        crop_size: 256
        rescale: true
        rescale_size: 256
        split: train
    test:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/test_large
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'test'
