model:
  base_learning_rate: 4.5e-06
  target: taming.models.refinement_ae.MaskPartialEncoderModel
  params:
    ckpt_path: logs/2023-05-06T18-14-51_places256_partialencoder_1024/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 1024
    image_key: "image"
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/places256_vqgan1024_BASE/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    ddconfig:
      padding_free: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 20
    train:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/data_large
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'train'
    test:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/test_large
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'test'
