model:
  base_learning_rate: 4.5e-06
  target: taming.models.refinement_ae.RefinementDecoder
  params:
    ckpt_path: logs/2023-03-14T01-04-23_refinement_debug/checkpoints/last.ckpt
    embed_dim: 512
    n_embed: 1024
    image_key: "image"
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/places_256_vqgan_BASEMODEL/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 8192
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    lossconfig:
      target: taming.modules.losses.vqperceptual.PIPSWithDiscriminator
      params:
        pixelloss_weight: 0.0
        perceptual_weight: 0.1
        r1_weight: 0.0
        perceptual_filter:
        - 3
        - 4
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    train:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/data_large
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'train'
