model:
  base_learning_rate: 4.5e-06
  target: taming.models.inpainting_master.InpaintingMaster
  params:
    # ckpt_path: logs/2023-04-18T16-17-51_debug/checkpoints/last.ckpt
    stage: final # vq | encoder | decoder | maskgit | final
    encoder_choice: refined # vq | refined
    image_key: image
    ################# VQ model configuration ##########
    vqmodel_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/2023-03-30T02-43-38_places256_vqgan_cont/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 8192
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
          params:
            disc_conditional: False
            disc_in_channels: 3
            disc_start: 1
            disc_weight: 0.8
            codebook_weight: 1.0
    ################## Encoder configuration #########################3
    encoder_config:
      target: taming.models.refinement_ae.MaskPartialEncoderModel
      params:
        ckpt_path: logs/2023-04-12T14-25-22_places256_maskencoder_cr48/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 8192
        image_key: "image"
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
    ################## Decoder configuration #########################3
    decoder_config:
      target: taming.models.refinement_ae.RefinementAE
      params:
        ckpt_path: logs/2023-04-17T16-42-06_places256_decoder_partialconv_randommask/checkpoints/last.ckpt
        # ckpt_path: logs/2023-04-05T07-50-07_places256_refinement_tamencoder_cont/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 8192
        image_key: image
        restriction: true
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.PIPSWithDiscriminator
          params:
            pixelloss_weight: 1.0
            perceptual_weight: 1.0
            r1_weight: 0.0
            disc_conditional: false
            disc_in_channels: 4
            disc_start: 1
            disc_weight: 0.8
    ################## Transformer configuration #########################3
    transformer_config:
      target: taming.models.maskgit.MaskGIT
      params:
        ckpt_path: /data/Haiwei/taming_ckpts/2023-04-18T16-34-25_places256_maskgit_abs_seq_ly40_cont/checkpoints/last.ckpt
        cond_stage_key: segmentation
        sampling_ratio: 0.2
        attention_extent: mask
        mask_on_latent: false
        transformer_config:
          target: taming.modules.transformer.mingpt.GPT
          params:
            vocab_size: 8193
            block_size: 512  # 257
            n_layer: 40 # 24,40
            n_head: 16
            n_embd: 1408
            embd_pdrop: 0.0
            resid_pdrop: 0.0
            attn_pdrop: 0.0
        cond_stage_config: "__is_unconditional__"
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    train:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/data_large
        crop_size: 256
        rescale: true
        rescale_size: 256
        split: train
    test:
      target: taming.data.places365.Places
      params:
        dataroot: /data/Haiwei/Datasets/Places365/test_large
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'test'
