model:
  base_learning_rate: 4.5e-06
  target: taming.models.inpainting_master.InpaintingMaster
  params:
    # ckpt_path: logs/2023-04-18T16-17-51_debug/checkpoints/last.ckpt
    stage: final # vq | encoder | decoder | maskgit | final
    encoder_choice: refined # vq | refined
    image_key: image
    ################# VQ model configuration ##########
    vqmodel_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/places256_vqgan1024_BASE/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
          params:
            disc_conditional: False
            disc_in_channels: 3
            disc_start: 1
            disc_weight: 0.8
            codebook_weight: 1.0
    ################## Encoder configuration #########################3
    encoder_config:
      target: taming.models.refinement_ae.MaskPartialEncoderModel
      params:
        ckpt_path: logs/2023-05-26T15-25-34_places256_partialencoder_1024_cont/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        image_key: "image"
        ddconfig:
          clamp_ratio: 0.25
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
    ################## Decoder configuration #########################3
    decoder_config:
      target: taming.models.refinement_ae.RefinementAE
      params:
        ckpt_path: logs/ckpts/decoder_beta_restriction.ckpt
        # ckpt_path: logs/2023-07-08T03-40-46_decoder_final_finetune/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        image_key: image
        restriction: true
        ddconfig:
          padding_free: false
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.vqperceptual.PIPSWithDiscriminator
          params:
            pixelloss_weight: 1.0
            perceptual_weight: 1.0
            r1_weight: 0.0
            disc_conditional: false
            disc_in_channels: 4
            disc_start: 1
            disc_weight: 0.8
    ################## Transformer configuration #########################3
    transformer_config:
      target: taming.models.maskgit.MaskGIT
      params:
        ckpt_path: logs/2023-06-30T12-34-38_places_maskgit_1024/checkpoints/last.ckpt
        cond_stage_key: segmentation
        sampling_ratio: 0.2
        attention_extent: mask
        mask_on_latent: false
        transformer_config:
          target: taming.modules.transformer.mingpt.GPT
          params:
            vocab_size: 1025
            block_size: 257  
            n_layer: 24 # 24,40
            n_head: 16
            n_embd: 1408
            embd_pdrop: 0.0
            resid_pdrop: 0.0
            attn_pdrop: 0.0
        cond_stage_config: "__is_unconditional__"
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    test:
      target: taming.data.places365.Places
      params:
        dataroot: /home/ICT2000/chenh/Haiwei/Datasets/Places365/val_large
        maskroot: /home/ICT2000/chenh/Haiwei/Datasets/Places365/masks_val_512_eval
        crop_size: 256
        rescale: True
        rescale_size: 256
        split: 'test'
